package lab6_hangman;

public class RandomAnimal {

	// This class has a single data member, an array (or list) of animals.
	private static String[] animals = new String[] {
			"Aardvark", 
			"Albatross", 
			"Alligator", 
			"Alpaca", 
			"Anaconda", 
			"Ant", 
			"Anteater", 
			"Antelope", 
			"Ape", 
			"Aphid", 
			"Armadillo", 
			"Baboon", 
			"Badger", 
			"Barnacle", 
			"Barracuda", 
			"Bass", 
			"Bat", 
			"Bear", 
			"Beaver", 
			"Bee", 
			"Beetle", 
			"Bird", 
			"Bison", 
			"Blackbird", 
			"Bluejay", 
			"Boar", 
			"Bobcat", 
			"Buffalo", 
			"Butterfly", 
			"Buzzard", 
			"Camel", 
			"Cardinal", 
			"Caribou", 
			"Carp", 
			"Cat", 
			"Caterpillar", 
			"Catfish", 
			"Centipede", 
			"Chameleon", 
			"Cheetah", 
			"Chickadee", 
			"Chicken", 
			"Chimpanzee", 
			"Chinchilla", 
			"Chipmunk", 
			"Clam", 
			"Clownfish", 
			"Cobra", 
			"Cockroach", 
			"Cod", 
			"Condor", 
			"Coral", 
			"Cougar", 
			"Coyote", 
			"Crab", 
			"Crane", 
			"Crayfish", 
			"Cricket", 
			"Crocodile", 
			"Crow", 
			"Cuckoo", 
			"Damselfly", 
			"Deer", 
			"Dingo", 
			"Dinosaur", 
			"Dog", 
			"Dolphin", 
			"Donkey", 
			"Dove", 
			"Dragonfly", 
			"Duck", 
			"Eagle", 
			"Earthworm", 
			"Eel", 
			"Egret", 
			"Elephant", 
			"Elk", 
			"Emu", 
			"Falcon", 
			"Ferret", 
			"Finch", 
			"Firefly", 
			"Fish", 
			"Flamingo", 
			"Flea", 
			"Fly", 
			"Fox", 
			"Frog", 
			"Gazelle", 
			"Gecko", 
			"Gerbil", 
			"Gibbon", 
			"Giraffe", 
			"Gnat", 
			"Gnu", 
			"Goat", 
			"Goldfish", 
			"Goose", 
			"Gopher", 
			"Gorilla", 
			"Grasshopper", 
			"Grouse", 
			"Haddock", 
			"Halibut", 
			"Hamster", 
			"Hawk", 
			"Hedgehog", 
			"Heron", 
			"Herring", 
			"Hippopotamus", 
			"Hornet", 
			"Horse", 
			"Hummingbird", 
			"Hyena", 
			"Iguana", 
			"Impala", 
			"Jackal", 
			"Jaguar", 
			"Jellyfish", 
			"Kangaroo", 
			"Koala", 
			"Kookabura", 
			"Ladybug", 
			"Lamprey", 
			"Lark", 
			"Lemming", 
			"Lemur", 
			"Leopard", 
			"Lion", 
			"Lizard", 
			"Llama", 
			"Lobster", 
			"Macaw", 
			"Mackerel", 
			"Manatee", 
			"Meerkat", 
			"Mink", 
			"Mockingbird", 
			"Mole", 
			"Mongoose", 
			"Monkey", 
			"Moose", 
			"Mosquito", 
			"Moth", 
			"Mouse", 
			"Mule", 
			"Newt", 
			"Nightingale", 
			"Octopus", 
			"Opossum", 
			"Orangutan", 
			"Ostrich", 
			"Otter", 
			"Owl", 
			"Oyster", 
			"Panda", 
			"Panther", 
			"Parrot", 
			"Partridge", 
			"Pelican", 
			"Penguin", 
			"Pheasant", 
			"Pig", 
			"Pigeon", 
			"Porcupine", 
			"Porpoise", 
			"Quail", 
			"Rabbit", 
			"Raccoon", 
			"Ram", 
			"Rat", 
			"Raven", 
			"Reindeer", 
			"Rhinoceros", 
			"Salamander", 
			"Salmon", 
			"Sandpiper", 
			"Sardine", 
			"Scorpion", 
			"Seahorse", 
			"Seal", 
			"Shark", 
			"Sheep", 
			"Shrew", 
			"Skunk", 
			"Sloth", 
			"Snail", 
			"Snake", 
			"Sparrow", 
			"Spider", 
			"Squid", 
			"Squirrel", 
			"Starling", 
			"Stingray", 
			"Stork", 
			"Swallow", 
			"Swan", 
			"Tapir", 
			"Tarantula", 
			"Tiger", 
			"Toad", 
			"Trout", 
			"Turkey", 
			"Turtle", 
			"Viper", 
			"Vulture", 
			"Wallaby", 
			"Walrus", 
			"Wasp", 
			"Weasel", 
			"Whale", 
			"Wolf", 
			"Wolverine", 
			"Wombat", 
			"Woodpecker", 
			"Worm", 
			"Wren", 
			"Yak", 
			"Zebra"
	};
	
	// Note that there is no constructor in this class. 
	// all methods and data members are "static" meaning that there is only 
	// one per class. No objects will be instantiated from this class.
	
	// This is the method we really want. It just returns one of the animals
	// from the list, randomly distributed.
	public static String getRandomAnimal () {
		
		// get a random integer between 1 and the size of the animal array (list)
		int i = randomInt (1,animals.length);
		
		// in java, array indexes go from 0 to size of array -1, 
		// not from 1 to size of array.
		i=i-1;
		
		// so now, i is guaranteed to be "in bounds" 
		return animals[i];

	}
	
	// return a randomly distribute integer between low and high 
	// (including low and high end points).
	//
	// We used a method like this before in the oracle program within the Methods module... 
	// private means we are not exposing this method for use by code outside this class. 
	// We are just using this method from within this class.
	private static int randomInt (int low, int high) {
		
		int range = high - low + 1;
		
		// Math.random() returns a number evenly distributed between 0 and 1
		double r = (Math.random() * range) + low;
		
		return (int) r;
	}

}
